export const cars = [
  {
    id: 0,
    title: "Porsche 718 Cayman",
    description: "Die 718 Modelle sind toll",
    detailedDescription:
      "Der Porsche 718 Cayman Typ 982 ist ein nach umfangreicher Modellpflege des Typs 981 gebauter Mittelmotor-Sportwagen der Porsche AG. Porsche selbst bezeichnet ihn als dritte Generation. Er hat die gleiche technische Plattform wie der Anfang 2016 vorgestellte Porsche 718 Boxster (Typ 982). Der Sportwagen wurde auf der Beijing Motor Show im April 2016 der Öffentlichkeit vorgestellt. Porsche führte danach den Boxster und Cayman unter der Baureihe 718 zusammen. Während der Cayman als eigene Baureihe bei 987 und 981 preislich oberhalb des Boxsters lag, ist nunmehr die Cabrio-Version 718 Boxster mit Ausnahme von Cayman GT4 bzw. Cayman GT4 RS im Vergleich zum Boxster Spyder bzw. Boxster Spyder RS die teurere Ausführung.",
    price: "72'100.00",
    src: "porsche1",
  },
  {
    id: 1,
    title: "Porsche 911 GT3",
    description: "Sportler wissen: Für leistungen",
    detailedDescription:
      "Als Porsche 911 GT3 werden die seit 1999 gebauten Sportversionen der Porsche 911 mit wassergekühltem Saugmotor bezeichnet. Die von 1972 bis 1997 produzierten Sportversionen des 911 mit luftgekühltem Saugmotor, die seine direkten Vorgänger sind, hatten die Bezeichnung Carrera RS. Aktuell basiert die GT3-Version auf dem 911 (992). Wie alle Porsche-911-GT-Modelle zeichnet sich auch der 911 GT3 durch Verzicht auf die zur sportlichen Fortbewegung nicht notwendigen Komfortmerkmale aus. Somit verkörpert er für einige Automobil-Puristen und vor allem für viele Porsche-Begeisterte die von ihnen bevorzugte Konzentration auf die zum sportlichen Fahren wesentliche Ausstattung. Ähnlich seinen turbogeladenen Schwestermodellen Porsche 911 GT1 und 911 GT2 ist auch der GT3 in vielerlei Hinsicht vom Motorsport inspiriert; er ist die Straßenversion des jeweils aktuell im Porsche Supercup eingesetzten 911-GT3-Cup-Rennwagens und nur so weit modifiziert, wie es für einen eventuellen alltäglichen Gebrauch und insbesondere den Erhalt einer Straßenzulassung notwendig ist.",
    price: "215'900.00",
    src: "porsche2",
  },
  {
    id: 2,
    title: "Porsche GT3 Tokyo",
    description: "Sportler wissen: Tokyo",
    detailedDescription:
      "Formula E is probably the most innovative racing series in the world. Because here, nobody knows what the future has in store. But at Automobilist, we have chosen to dream the difference - a future where the E-Prix zips at never-seen-before speeds. On futuristic tracks in Japan, lighting up with nothing but the sheer energy and friction being generated by the cars, welcome to racing more than a hundred years away. But imagination met technology in 2020, as Porsche headed into the final corner of its debut season with Formula E. Click here to explore.",
    price: "315'900.00",
    src: "porsche3",
  },
  {
    id: 3,
    title: "Porsche 911 Oldschool",
    description: "Sportler wissen: oldschool",
    detailedDescription:
      "Der Porsche 911 ist ein Sportwagen von Porsche und der Nachfolger des Porsche 356. Der kurz „Neunelfer“, oder nur „Elfer“ genannte Porsche 911 ist das bekannteste Fahrzeug des Stuttgarter Unternehmens und gilt als Inbegriff der Marke. Porsche stellte das später so genannte „Urmodell“ im September 1963 vor. Das „G-Modell“ ab 1973 bildete dann die zweite Generation der inzwischen acht Generationen der 911er-Modellreihe (Stand 2022). ",
    price: "345'200.00",
    src: "porsche4",
  },
  {
    id: 4,
    title: "Porsche 918",
    description: "Sportler wissen: schnell",
    detailedDescription:
      "Unter der Typenbezeichnung Porsche 918 hat der Sportwagenhersteller Porsche bislang zwei verschiedene Fahrzeugkonzepte vorgestellt, die beide als Hochleistungs-Mittelmotor-Fahrzeuge mit Hybridantrieb ausgelegt sind. Der 918 Spyder ist ein zweitüriger und zweisitziger Supersportwagen mit einer Roadster-Karosserie. Er wurde am 1. März 2010 beim Genfer Auto-Salon vorgestellt, die Markteinführung war im November 2013. Der Grundpreis lag bei 768.026 Euro,[2] für gewichtsoptimierte Fahrzeuge mit Weissach-Paket bei 839.426 Euro.[3] Die Produktion des auf 918 Exemplare limitierten Modells wurde am 19. Juni 2015 eingestellt.[1] Der 918 Spyder soll jedoch weiterhin als Impulsgeber für technische Entwicklungen dienen. Dabei wird der Schwerpunkt insbesondere auf der Weiterentwicklung des Antriebskonzepts liegen, bestehend aus zwei Elektromotoren und einem Verbrennungsmotor. Der 918 RSR ist eine auf dem Spyder basierende Studie eines Rennwagens mit Komponenten der Antriebstechnik aus dem Porsche 997 GT3 R Hybrid. Der RSR wurde im Januar 2011 auf der Detroiter North American International Auto Show vorgestellt. Für das Design war Michael Mauer[5] verantwortlich. Der damalige Porsche-Entwicklungschef Wolfgang Dürheimer wurde für das Auto von dem Automagazin Top Gear als Mann des Jahres 2010 ausgezeichnet",
    price: "768'026.40",
    src: "porsche5",
  },
  {
    id: 5,
    title: "Porsche Macan",
    description: "Family",
    detailedDescription:
      "Der Porsche Macan ist ein Sport Utility Vehicle (SUV) des deutschen Automobilherstellers Porsche. Das Modell wurde am 20. November 2013 vorgestellt und wird seit Anfang 2014 vermarktet. Hinsichtlich den Abmessungen ist der Macan kleiner als der Cayenne und basiert auf dem Audi Q5 8R (modularer Längsbaukasten). Die vollständige Fertigung und Montage des Macan findet im Porsche-Werk Leipzig statt. Das Modell stellt die fünfte Modellreihe von Porsche dar.[2] Der Grundpreis des Macan liegt in Deutschland bei 62.917 Euro (Juli 2021).[3] Nachdem Porsche einen Absatz von jährlich über 60.000 Stück plante,[4] wurden bis Juni 2015 bereits über 100.000 Wagen verkauft.",
    price: "79'600.00",
    src: "porsche6",
  },
  {
    id: 6,
    title: "Porsche Cayenne",
    description: "Family, aber teuer",
    detailedDescription:
      "Der Porsche Cayenne ist ein Modell des deutschen Automobilherstellers Porsche. Mit dem 2002 eingeführten Wagen erweiterte Porsche seine bis dahin nur aus Sportwagen bestehende Modellpalette um ein Sport Utility Vehicle (SUV). Der Hauptmarkt des Cayenne sind die Vereinigten Staaten. Der Porsche Cayenne (Typ 9PA) wurde von 2002 bis 2010 gebaut, seit 2007 mit Direkteinspritzer-Motoren und einer Modellpflege. Das Nachfolgemodell Porsche Cayenne (Typ 92A) wurde von 2010 bis 2017 gebaut. Am 29. August 2017 fand die Premiere der dritten Generation des Porsche Cayenne (Typ PO536) statt;[1] sie wurde auf der Internationalen Automobil-Ausstellung im September 2017 der Öffentlichkeit präsentiert.",
    price: "102'100.00",
    src: "porsche7",
  },
  {
    id: 7,
    title: "Porsche 919 Hybrid",
    description: "Sportler wissen: easy win",
    detailedDescription:
      "Der Porsche 919 Hybrid (Eigenschreibweise: 919 hybrid) ist ein Prototyp aus der Sportwagenklasse LMP1, der von 2014 bis 2017 in der FIA-Langstrecken-Weltmeisterschaft (WEC) (einschließlich des 24-Stunden-Rennens von Le Mans) an den Start ging. Das Fahrzeug hat einen Hattrick mit drei aufeinanderfolgenden Gesamtsiegen beim 24-Stunden-Rennen von Le Mans in den Jahren 2015, 2016 und 2017 erreicht. Das Siegerfahrzeug 2015 hatte bei einer Rundenanzahl von 395 insgesamt 876,9 kWh rekuperieren können. Am 9. April 2018 gab Porsche bekannt, mit einer Evo-Version des 919 Hybrid einen inoffiziellen Rundenrekord von 1:41,770 Minuten gefahren von Porsche-Werkspilot Neel Jani auf dem Circuit de Spa-Francorchamps aufgestellt zu haben. Am 29. Juni 2018 fuhr Porsche-Werkspilot Timo Bernhard mit dem 919 Hybrid Evo auf der Nordschleife eine neue Bestzeit von 5:19,546 Minuten. Damit wurde der bisherige Rekord um 51,58 Sekunden verbessert. Die Durchschnittsgeschwindigkeit der Rekordrunde betrug 234,69 km/h.",
    price: "25'000'000.00",
    src: "porsche8",
  },
  {
    id: 8,
    title: "Porsche 911 Dakar",
    description: "Sportler wissen: offroad und so",
    detailedDescription:
      "Jubiläen sind etwas Schönes und immer eine adäquate Gelegenheit an die Erfolge vergangener Tage zu erinnern. Dass man aber auch ganz ohne runden Geburtstag sich selbst und die Vergangenheit feiern kann, beweist Porsche mit dem 911 Dakar. Der soll nämlich an den ersten Gesamtsieg bei der Rallye Paris Dakar 1984 erinnern. Wer jetzt aber an ein paar bunte Aufkleber und gravierte Bleche mit Seriennummer denkt, liegt falsch. Zumindest ein bisschen. Die gibt es natürlich auch, damit ist es beim 911 Dakar aber nicht getan. Denn Porsche hat den Elfer kräftig überarbeitet und den Sportwagen so fit für den Einsatz im Gelände gemacht. Doch der Reihe nach.",
    price: "272'000.00",
    src: "porsche9",
  },
];
